spring:
  zipkin:
    #    base-url: http://localhost:7008
    enabled: true
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin2
    service:
      name: ${spring.application.name}

  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:123456}
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:192.168.1.200}
    virtualHost: ${RABBITMQ_VHOST:dy}
