---
server:
  tomcat:
    max-threads: 128
    uri-encoding: UTF-8
  gateway:
    name: gateway

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      override-none: true
  zipkin:
#    base-url: http://localhost:7008
    rabbitmq:
      queue: zipkin2
    sender:
      type: RABBIT
  sleuth:
    sampler:
      probability: 1.0
    scheduled:
      skipPattern: org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask
  rabbitmq:
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:123456}
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:192.168.1.200}
    virtualHost: ${RABBITMQ_VHOST:dy}
  datasource:
    url: jdbc:mysql://${DATASOURCE_HOST:120.79.106.197}:${DATASOURCE_PORT:3306}/${DATASOURCE_NAME:dy-dev}?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
    druid:
      maxActive: ${DATASOURCE_DRUID_MAXACTIVE:4}
      initialSize: ${DATASOURCE_DRUID_INITIALSIZE:4}
      minIdle: ${DATASOURCE_DRUID_MINIDLE:4}
      maxWait: ${DATASOURCE_DRUID_MAXWAIT:60000}
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false

#    property-naming-strategy: SNAKE_CASE ！！坑在这

---
#mybatis:
#  # Mybatis配置Mapper路径
#  mapper-locations: classpath:mapper/*.xml
##  type-aliases-package: com.witc.common.moduals.xx.entity

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.witc.common.moduals.xx.entity
#  typeEnumsPackage: com.witc.common.moduals.xx.entity
  global-config:
    # 数据库相关配置
    sql-parser-cache: true
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

---
## Discovery Center
eureka:
  instance:
    # 以IP方式注册到注册中心，默认是应用名
    prefer-ip-address: true
    # 与注册中心的周期心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    # 续约到期时间
    lease-expiration-duration-in-seconds: 30
    # 节点状态和安全检查路径
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator

---
#springboot2.0的时候必须配置include: '*'
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
api:
  url:
    pre: /api
session:
  checked:
    redirect:
      url: /login
base:
  boot:
    is_need_validate: true

witc:
  core:
    jwt:
      enable: false
    log:
      routingKey: witc_sys_log_queue
  tenant:
    column: company_id
    superAdminTenantId: -1
    tables:
#      - sys_user  #sysUser自己控制数据隔离
      - equipment_day_static
      - equipment_logger
      - sys_companyinfo
      - sys_company_lable
      - equipment_lc_data
      - sys_log

